services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: event-management-api:latest
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_PATH: /app/data/event_management.db
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./data:/app/data
    restart: unless-stopped
